const appname = "Infinity Mart";
const appversion = "Version 1.0.0";
const credits = "@Infinity_devs";
const email = "Email";
const emailHint = "abc@infinity.com";
const password = "Password";
const passwordHint = "******";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "Asmit Gupta";
const forgetPass = "Forget Password";
const login = "Log in";
const signUp = "Sign Up";
const createnewAccount = "Create a new Account";
const loginwith = "Log in with";
const privacyPolicy = "Privacy Policy";
const termandPrivacy = "Terms and Privacy";
const alreadyHaveAccount = "Already have an account? ";
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
// home screen strings

const searchanything = "Search Anything...",
    todayDeal = "Today's Deal",
    flashsale = "Flash Sale",
    topseller = "Top Seller",
    topcateg = "Top Categories",
    brand = "Brand",
    featuredCateg = "Featured Categories";
